### ISSUE TITLE
ReferenceError: ret is not defined

### ISSUE THREAD

**Issue by lathanbritz** [jagenjo/litegraph.js#363]
###Version 7.1.2
logicAnd is broken

```
litegraph.js:19592 Uncaught (in promise) ReferenceError: ret is not defined
    at logicAnd.onExecute (litegraph.js:19592:9)
    at LGraph2.runStep (litegraph.js:1028:34)
    at on_frame2 (litegraph.js:934:22)
    at LGraph2.start (litegraph.js:939:13)
    at Proxy.handleOnToggle (LGraph.vue:97:32)
    at _createElementVNode.onClick._cache.<computed>._cache.<computed> (LGraph.vue:6:95)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:164:21)
    at HTMLButtonElement.invoker (runtime-dom.esm-bundler.js:369:13)
```

**Comment by jagenjo** [comment]
fixed by @atlasan
